apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ct293-a001-uf-v1-ingress
  namespace: ct293-a001-uf-v1
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - tgadev.toruslowcode.com
      secretName: ct293-a001-uf-v1-tls
  rules:
    - host: tgadev.toruslowcode.com
      http:
        paths:
          - path: /ct293/ag001/a001/v1
            pathType: Prefix
            backend:
              service:
                name: ct293-a001-uf-generator
                port:
                  number: 443