apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ct003-oprmatrix-uf-v1-ingress
  namespace: ct003-oprmatrix-uf-v1
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - tgadev.toruslowcode.com
      secretName: ct003-oprmatrix-uf-v1-tls
  rules:
    - host: tgadev.toruslowcode.com
      http:
        paths:
          - path: /ct003/ag001/oprmatrix/v1
            pathType: Prefix
            backend:
              service:
                name: ct003-oprmatrix-uf-generator
                port:
                  number: 443