apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ct003-oprmatrix-df-v1-ingress
  namespace: ct003-oprmatrix-df-v1
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - tgadev.toruslowcode.com
      secretName: ct003-oprmatrix-df-v1-tls
  rules:
    - host: tgadev.toruslowcode.com
      http:
        paths:
          - path: /ct003/ag001/oprmatrix/v1/api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ct003-oprmatrix-df-generator
                port:
                  number: 443